links/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('links.views',
    url(r'^add_link$', 'add_link', name='add_link'),
)

locations/urls.py
from django.conf.urls.defaults import *

from locations.views import *

urlpatterns = patterns('locations.views',
    url(r'^(?P<loc_id>\d+)$', InfoView.as_view(), name='location_info', kwargs={'view': 'location_info'}),
    url(r'^(?P<loc_id>\d+)/wall$', 'location_view', name='location_wall', kwargs={'view': 'location_wall'}),
    url(r'^(?P<loc_id>\d+)/map$', 'location_view', name='location_map', kwargs={'view': 'location_map'}),
    url(r'^(?P<loc_id>\d+)/web_observers', WebObserversView.as_view(), name='web_observers', kwargs={'view': 'web_observers'}),
    url(r'^(?P<loc_id>\d+)/participants', ParticipantsView.as_view(), name='participants', kwargs={'view': 'participants'}),
    url(r'^(?P<loc_id>\d+)/violations', ViolationsView.as_view(), name='violations', kwargs={'view': 'violations'}),
    url(r'^(?P<loc_id>\d+)/protocols', ProtocolsView.as_view(), name='protocols', kwargs={'view': 'protocols'}),
    url(r'^(?P<loc_id>\d+)/links', LinksView.as_view(), name='links', kwargs={'view': 'links'}),
    url(r'^(?P<loc_id>\d+)/organizations', OrganizationsView.as_view(), name='organizations', kwargs={'view': 'organizations'}),

    # Redirect, not used anymore
    url(r'^(?P<loc_id>\d+)/supporters', 'location_supporters', name='supporters'),

    url(r'^get_sub_regions$', 'get_sub_regions', name='get_sub_regions'),
    url(r'^goto_location$', 'goto_location', name='goto_location'),

    url(r'^locations_data$', 'locations_data', name='locations_data'),
    url(r'^boundaries_data$', 'boundaries_data', name='boundaries_data'),
)

protocols/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('protocols.views',
    url(r'^(?P<protocol_id>\d+)$', 'protocol_view', name='protocol_view'),
    url(r'^upload$', 'upload_protocol', name='upload_protocol'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template

from locations.sitemap import LocationSitemap
from organizations.sitemap import OrganizationSitemap

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('grakon.urls')),
    url(r'^', include('navigation.urls')),
    url(r'^', include('users.urls')),
    url(r'^', include('reports.urls')),
    url(r'^', include('registration.urls')),
    url(r'^', include('organizations.urls')),
    url(r'^', include('search.urls')),
    url(r'^links/', include('links.urls')),
    url(r'^location/', include('locations.urls')),
    url(r'^violation/', include('violations.urls')),
    url(r'^protocol/', include('protocols.urls')),
    url(r'^loginza/', include('loginza.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    (r'^robots\.txt$', direct_to_template, {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {
        'locations': LocationSitemap,
        'organizations': OrganizationSitemap,
    }}),

    url(r'^%s/' % settings.ADMIN_PREFIX, include(admin.site.urls)),
)

try:
    import captcha
    urlpatterns += patterns('',
        url(r'^captcha/', include('captcha.urls')),
    )
except ImportError:
    pass

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

links/models.py
# coding=utf8
from django.db import models

from grakon.models import Profile
from locations.models import Location

class Link(models.Model):
    location = models.ForeignKey(Location)
    user = models.ForeignKey(Profile, related_name='links')
    name = models.CharField(max_length=200)
    url = models.URLField()
    time = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('url', 'location')

    def __unicode__(self):
        return self.url

users/models.py
# -*- coding:utf-8 -*-
from django.db import models

from grakon.models import Profile
from locations.models import Location
from organizations.models import Organization

ROLE_CHOICES = (
    ('observer', u'Наблюдатель'),
    ('voter', u'Избиратель'),
    ('journalist', u'Представитель СМИ'),
    ('lawyer', u'Юрист'),
    ('prosecutor', u'Представитель прокуратуры'),
    ('member', u'Член избирательной комиссии'),
    ('authority', u'Представитель власти'),
    ('supporter', u'Поддержка наблюдателей'),
)
ROLE_TYPES = dict(ROLE_CHOICES)

class RoleManager(models.Manager):
    def get_participants(self, query):
        participants = {}

        roles_by_type = {}
        for role_id, role_type in list(self.filter(query).values_list('id', 'type')):
            roles_by_type.setdefault(role_type, []).append(role_id)

        role_ids = []
        for role_type in roles_by_type:
            # TODO: Temporary hack
            role_ids += roles_by_type[role_type][:10]

        for role in list(Role.objects.filter(id__in=role_ids).select_related('user', 'organization')):
            participants.setdefault(role.type, []).append(role)

        # Sort participants by name and limit the length of the lists
        for role in participants:
            show_name_participants = filter(lambda p: p.user.show_name, participants[role])
            other_participants = filter(lambda p: not p.user.show_name, participants[role])

            participants[role] = sorted(show_name_participants, key=lambda r: r.user.username.lower())
            participants[role] += sorted(other_participants, key=lambda r: r.user.username.lower())

        return participants

class Role(models.Model):
    user = models.ForeignKey(Profile, related_name='roles')
    location = models.ForeignKey(Location)
    type = models.CharField(max_length=10, choices=ROLE_CHOICES, db_index=True)

    organization = models.ForeignKey(Organization, blank=True, null=True, db_index=True)
    data = models.CharField(max_length=200, default='', blank=True)
    verified = models.BooleanField(default=False, db_index=True)

    time = models.DateTimeField(auto_now=True)

    objects = RoleManager()

    class Meta:
        unique_together = ('user', 'location', 'type')

    def type_name(self):
        return ROLE_TYPES[self.type]

    def __unicode__(self):
        return unicode(self.user) + ' is ' + self.type + ' at ' + unicode(self.location)

class Contact(models.Model):
    user = models.ForeignKey(Profile, related_name='contacts')
    contact = models.ForeignKey(Profile, related_name='have_in_contacts')
    time = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'contact')

    def __unicode__(self):
        return unicode(self.user) + ' has ' + unicode(self.contact) + ' in contacts'

MEMBER_CHOICES = (
    ('chairman', u'Председатель'),
    ('vice', u'Заместитель председателя'),
    ('secretary', u'Секретарь'),
    ('prg', u'Член с правом решающего голоса'),
    ('psg', u'Член с правом совещательного голоса'),
    ('other', u'Другое'),
)

PARTY_CHOICES = (
    ('ER', u'Единая Россия'),
    ('KPRF', u'КПРФ'),
    ('LDPR', u'ЛДПР'),
    ('SR', u'Справедливая Россия'),
    ('Prohorov', u'Штаб Прохорова'),
    ('Yabloko', u'Яблоко'),
    ('other', u'Другое'),
)

class Message(models.Model):
    from_user = models.ForeignKey(Profile, verbose_name=u'От пользователя', related_name='sender')
    to_user = models.ForeignKey(Profile, verbose_name=u'Пользователю', related_name='reciever')
    title = models.CharField(u'Тема', max_length=100)
    body = models.TextField(u'Сообщение')
    show_email = models.BooleanField(u'Показывать email', default=False)
    time = models.DateTimeField(auto_now=True)

class CommissionMember(models.Model):
    last_name = models.CharField(u'Фамилия', max_length=50)
    first_name = models.CharField(u'Имя', max_length=50)
    middle_name = models.CharField(u'Отчество', max_length=50, blank=True)
    role = models.CharField(u'Должность', max_length=100, choices=MEMBER_CHOICES)
    party = models.CharField(u'Кем выдвинут', max_length=100, choices=PARTY_CHOICES)
    job = models.CharField(u'Место работы', max_length=100, blank=True)

    user = models.ForeignKey(Profile)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(auto_now=True)

class WebObserver(models.Model):
    start_time = models.IntegerField(u'Начало наблюдения', help_text=u'Местное время')
    end_time = models.IntegerField(u'Окончание наблюдения')
    capture_video = models.BooleanField(u'Будет ли производиться захват видео', default=False)
    url = models.URLField(u'Ссылка на видео', blank=True)

    user = models.ForeignKey(Profile)
    location = models.ForeignKey(Location)
    time = models.DateTimeField(auto_now=True)

class UnsubscribedUser(models.Model):
    user = models.ForeignKey(Profile, unique=True)
    time = models.DateTimeField(auto_now=True)

violations/models.py
# -*- coding:utf-8 -*-
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models

from locations.models import Location

VIOLATION_CHOICES = (
    ('1', u'Ограничение прав наблюдателя'),
    ('2', u'Необоснованное удаление с участка'),
    ('3', u'Вброс бюллетеней'),
    ('4', u'Массовая доставка избирателей на участок'),
    ('5', u'Групповое голосование по открепительным'),
    ('6', u'Давление начальства на избирателей'),
    ('7', u'Подкуп'),
    ('8', u'Непредоставление права голоса'),
    ('9', u'Незаконная агитация'),
    ('10', u'Нарушение на выездном голосовании'),
    ('11', u'Присутствие на участке посторонних лиц'),
    ('12', u'Нарушение правил подведения итогов'),
    ('13', u'Искажение результатов'),
    ('14', u'Невыдача копии протокола'),
    ('15', u'Другое'),
)

class Violation(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    source = generic.GenericForeignKey('content_type', 'object_id')

    violation_id = models.IntegerField(u'Идентификатор')
    type = models.CharField(u'Тип нарушения', max_length=15, choices=VIOLATION_CHOICES)
    text = models.TextField(u'Сообщение')
    location = models.ForeignKey(Location)
    time = models.DateTimeField(auto_now=True)
    url = models.URLField(u'Ссылка', blank=True, help_text=u'Ссылка на доказательства')

    class Meta:
        unique_together = ('content_type', 'object_id', 'violation_id')

    @models.permalink
    def get_absolute_url(self):
        return ('violation_view', (), {'violation_id': self.id})

links/views.py
# -*- coding:utf-8 -*-
from django.core.validators import URLValidator
from django.db import IntegrityError
from django.http import HttpResponse

from links.models import Link

def add_link(request):
    if request.method=='POST' and request.user.is_authenticated():
        try:
            location_id = int(request.POST.get('location', ''))
        except ValueError:
            return HttpResponse(u'Регион не найден')

        name = request.POST.get('name', '')
        if name == '':
            return HttpResponse(u'Введите название ссылки')

        url = request.POST.get('url', '')
        try:
            URLValidator().__call__(url)
        except Exception, e:
            return HttpResponse(u'Неправильный формат url')

        try:
            Link.objects.create(location_id=location_id, user=request.profile, url=url, name=name)
        except IntegrityError:
            return HttpResponse(u'Такая ссылка уже добавлена')

        return HttpResponse('ok')

    return HttpResponse(u'Ошибка')

organizations/views.py
# -*- coding:utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from grakon.models import Profile
from locations.models import Location
from organizations.forms import CreateOrganizationForm, EditOrganizationForm
from organizations.models import Organization, OrganizationCoverage, OrganizationRepresentative
from users.models import Role

class BaseOrganizationView(object):
    template_name = 'organizations/base.html'
    view = None # 'organization_info', 'organization_edit' or 'organization_create'
    model = Organization

    def get_object(self, queryset=None):
        return get_object_or_404(Organization.objects.select_related(),
                name=self.kwargs.get('name', ''))

    def get_representatives(self):
        if not hasattr(self, 'representatives'):
            self.representative_ids = OrganizationRepresentative.objects.filter(organization=self.object) \
                .values_list('user', flat=True)
            self.representatives = Profile.objects.filter(id__in=self.representative_ids)

    def get_context_data(self, **kwargs):
        ctx = super(BaseOrganizationView, self).get_context_data(**kwargs)

        organization = self.object

        self.get_representatives()
        is_representative = self.request.user.id in self.representative_ids

        location_ids = OrganizationCoverage.objects.filter(organization=organization).values_list('location_id', flat=True)
        locations = list(Location.objects.filter(id__in=location_ids).select_related())
        if None in location_ids:
            locations.append(None) # special processing for the whole country

        participants = Role.objects.get_participants(Q(organization=organization))
        counters = {}
        if organization.signup_observers:
            counters['observer'] = Role.objects.filter(organization=organization, type='observer').count()
        if organization.signup_journalists:
            counters['journalist'] = Role.objects.filter(organization=organization, type='journalist').count()

        ctx.update({
            'name': self.kwargs['name'],
            'view': self.view,
            'organization': organization,
            'locations': locations,
            'representatives': self.representatives,
            'participants': participants,
            'counters': counters,
            'is_representative': is_representative,
        })
        return ctx

class OrganizationInfoView(BaseOrganizationView, DetailView):
    view = 'organization_info'

organization_info = OrganizationInfoView.as_view()

class EditOrganizationView(BaseOrganizationView, UpdateView):
    form_class = EditOrganizationForm
    view = 'edit_organization'

@login_required
def edit_organization(request, name):
    # TODO: only representatives can edit (do redirect)
    return EditOrganizationView.as_view()(request, name=name)

class CreateOrganizationView(CreateView):
    template_name = 'organizations/create.html'
    form_class = CreateOrganizationForm
    model = Organization

    def form_valid(self, form):
        response = super(CreateOrganizationView, self).form_valid(form)

        profile = self.request.profile
        organization = self.object

        OrganizationRepresentative.objects.get_or_create(organization=organization, user=profile)

        OrganizationCoverage.objects.get_or_create(organization=organization, location=form.location)

        # Send email to us stating that new organization has registered
        subject = u'Зарегистрирована новая организация - %s' % organization.title

        message = u'Зарегистрирована новая организация:\n' \
                u'Название: %s\n' \
                u'Страница: http://grakon.org%s\n' \
                u'Сайт: %s\n' \
                u'Пользователь: http://grakon.org/user/%s\n' \
                u'Email: %s' % (
                organization.title, organization.get_absolute_url(), organization.website,
                profile.username, profile.user.email)

        send_mail(subject, message, 'admin@grakon.org', ['admin@grakon.org'], fail_silently=False)

        return response

create_organization = login_required(CreateOrganizationView.as_view())

locations/templates/locations/base.html
{% extends "base.html" %}

{% load elements %}

{% block title %}
Результаты президентских выборов -
{% if current_location.region %}{{ current_location.region }} - {% endif %}
{% if current_location.tik %}{{ current_location.tik }} - {% endif %}
{{ current_location }} - Гракон
{% endblock %}

{% block head %}
    <style type="text/css">
        .ym-col3 .ym-cbox {display: none;}
    </style>
{% endblock %}

{% block breadcrumbs %}
    {% include "elements/breadcrumbs.html" %}

    {% include "elements/results_table.html" %}
{% endblock %}

{% block left_column %}
    <h3 class="column_header column_header_icon"><span class="participants">Участники</span></h3>

    <div class="ym-clearfix">
        {% include "elements/left_panel.html" %}
    </div>
{% endblock %}

{% block right_column %}
    {% include "blocks/complaints.html" %}

    {% include "blocks/protocols.html" %}

    {% include "blocks/violations.html" %}

    {% include "blocks/web_observers.html" %}

    {% include "blocks/commission_members.html" %}

    {% include "blocks/links.html" %}

    {% include "elements/right_panel.html" %}

    {% include "dialogs/add_link.html" %}
    {% include "dialogs/add_commission_member.html" %}

    {% if user.is_authenticated %}
        <script type="text/javascript">
            // Add link
            $("#add_link_dialog").on("add_link_event", function(){
                $("#links_ul").append($("<li/>").append(
                    $("<a/>").attr("target", "_blank").attr("href", $("#link_url_input").val())
                        .text($("#link_name_input").val())
                ));
            });

            /*$("#report_link").click(function(){
                // TODO: depricate it
                $("#links_ul li").each(function(index){
                    var url = $(this).children("a").attr("href");
                    var text = $(this).text();
                    var a_copy = $("<a/>").attr("href", url).text(text);
                    var radio_btn = $("<input/>").attr("type", "radio").attr("name", "report_link_radio").attr("value", url);
                    $("#report_link_ul").append($("<li/>").append(radio_btn).append(a_copy));
                });
            });*/
        </script>
    {% endif %}
{% endblock %}

{% block content_header %}
    <h2 class="location_header">{{ current_location }}</h2>

    {% tabs "tabs" view "loc_id" loc_id "Сообщения&nbsp;" "location_wall" "services/disqus.html" "" "Карта" "location_map" "locations/map.html" "" "Информация" "location_info" "locations/info.html" "" "Участники" "participants" "locations/participants.html" "" %}

    {% include "services/disqus-counter.html" %}

    <script type="text/javascript">
        $("#add_commission_member, #add_commission_member1, #add_commission_member2").click(add_commission_member_dialog_init);
        {% if dialog %}
            $(document).ready(function(){
                become_{{ dialog }}_dialog_init();
            });
        {% endif %}
    </script>
{% endblock %}

locations/templates/locations/info.html
{% load elements %}

<p>
    <b>Адрес</b>: {{ current_location.postcode|default:"" }} {{ current_location.address|default:"Адрес недоступен" }}
</p>

<p>
    <b>Телефон</b>: {{ current_location.telephone|default:"Телефон недоступен" }}
</p>

{% if current_location.email %}
<p>
    <b>Email</b>: <a href="mailto:{{ current_location.email }}">{{ current_location.email }}</a>
</p>
{% endif %}

{% if not current_location.is_foreign or not current_location.is_tik %}
    <p>
        <b>Информация на сайте Центризбиркома:</b>
        <br/>
        {% if current_location.info_url %}
            <a href="{{ current_location.info_url }}" target="_blank">Информация о комиссии</a>
            <br/>
        {% endif %}
        <a href="{{ current_location.results_url }}" target="_blank">Официальные результаты выборов</a>
    </p>
{% endif %}

<p>
    <b>Состав комиссии:</b>
    <br/>

    <ul>
        {% for commission_member in commission_members %}
            <li>
                <b>{{ commission_member.last_name }} {{ commission_member.first_name }} {{ commission_member.middle_name }}</b>
                <br/>
                <i>Должность:</i> {{ commission_member.get_role_display }}
                <br/>
                <i>Кем выдвинут:</i> {{ commission_member.get_party_display }}
                {% if commission_member.job %}
                <br/>
                <i>Место работы:</i> {{ commission_member.job }}
                {% endif %}
            </li>
        {% empty %}
            <li><i>Пока не добавлено ни одного члена комиссии</i></li>
        {% endfor %}
    </ul>

    {% button "" "Добавить члена комиссии" "add_commission_member1" %}
</p>

locations/templates/locations/links.html
<h4>Полезные ресурсы</h4>

<ul id="links_ul">
    {% for link in links %}
        <li><a href="{{ link.url }}" target="_blank">{{ link.name }}</a></li>
    {% endfor %}
</ul>

locations/templates/locations/map.html
<script src="http://api-maps.yandex.ru/1.1/index.xml?key={{ YANDEX_MAPS_KEY }}&modules=pmap" type="text/javascript"></script>
<script type="text/javascript" src="{{ STATIC_URL }}libs/jquery.cookie.js"></script>
<script src="{{ STATIC_URL }}js/OpenLayers.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/OL_Yandex.js" type="text/javascript"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/map.js"></script>

<div class="center">
    <div id="publicElectionsMap" style="height:500px; min-width: 300px;"></div>
</div>
<a href="#" id="permalink">Постоянная ссылка на данный вид карты</a>

<script type="text/javascript">
    $(document).ready(function(){
        Grakon.init("{{ current_location.x_coord }}", "{{ current_location.y_coord }}", Grakon.Utils.getZoomForLevel({{ current_location.level }}+1));
    });
</script>

locations/templates/locations/organizations.html
<h4>Организации</h4>

<ul>
    {% for organization in organizations %}
        {% if organization.verified %}
            <li>
                {% include "elements/organization.html" %}
            </li>
        {% endif %}
    {% endfor %}
</ul>

locations/templates/locations/participants.html
<div class="search-filter">
    {% for role_type, role_name in ROLE_CHOICES %}
        {% if selected_role_type == role_type %}
            <b>{{ role_name }}</b>
        {% else %}
            <a href="{% url participants current_location.id %}?type={{ role_type }}" class="pseudolink">{{ role_name }}</a>
        {% endif %}
        &nbsp;&nbsp;&nbsp;
    {% endfor %}
</div>
<!--<div class="ext-search">
    <input type="text" class="text" value="Поиск среди наблюдателей" onfocus="if (this.value==this.defaultValue) this.value = ''" onblur="if (this.value=='') this.value = this.defaultValue" />
    <input type="button" class="search-btn" />
</div>-->

{% if selected_role_type %}
    <ul class="user_list">
        {% for role in participants %}
            {% with participant=role.user %}
                <li>{% include "elements/participant.html" %}
                    <br/>
                    <i>
                        {% if role.organization %}
                            {{ role.organization }}
                        {% else %}
                            {{ role.data }}
                        {% endif %}
                    </i>
                </li>
            {% endwith %}
        {% endfor %}
    </ul>
{% else %}
    <ul>
        {% for participant in users %}
            <li>{% include "elements/participant.html" %}</li>
        {% endfor %}
    </ul>
{% endif %}
<!--<div class="pages">
    <a href=""><img src="/static/images/icon_arrow_prev.gif" align="absmiddle" /></a>&nbsp;&nbsp;
    На страницу
    <strong>1</strong> |
    <a href="">2</a> |
    <a href="">3</a> |
    <a href="">4</a> |
    <a href="">5</a> |
    <a href="">6</a>
    &nbsp;&nbsp;<a href=""><img src="/static/images/icon_arrow_next.gif" align="absmiddle" /></a>

</div>-->

locations/templates/locations/protocols.html
{% load elements %}

<h4>Протоколы</h4>

<ul>
    {% for protocol in protocols %}
        <li>
            <a href="{{ protocol.get_absolute_url }}">Протокол №{{ protocol.id }}</a>
        </li>
    {% endfor %}
</ul>

{% button "" "Выложить протокол" "" "upload_protocol" "center" "В ближайшее время мы начнем собирать протоколы от участников площадки" %}

locations/templates/locations/supporters.html
{% load elements %}

<p>Чтобы принять участие в группе поддержки, придите со своими друзьями
в 8 часов вечера (сразу после завершения голосования) к избирательному участку.
Ваша задача - проследить, что наблюдатели получили заверенные копии протокола.</p>

<p>Известно, что после закрытия участков наблюдатели
остаются один на один с возможными нарушителями. Если вы будете снаружи,
то фальсификаторам будет сложнее убежать с мешком документов, печатями и т.д.,
а также выставить наблюдателей за дверь.</p>

<p>Подробнее о группах поддержки читайте <a href="{% url support_group_help %}">здесь</a>.</p>

<ul>
    {% for role in participants.supporter %}
        {% with participant=role.user %}
            <li>{% include "elements/participant.html" %}</li>
        {% endwith %}
    {% endfor %}
</ul>

{% button "" "Поддержать наблюдателей" "become_supporter1" %}

locations/templates/locations/violations.html
<h4>Нарушения</h4>

<ul>
    {% for violation in violations %}
        <li>
            <a href="{{ violation.get_absolute_url }}">{{ violation.get_type_display }}</a>
        </li>
    {% endfor %}
</ul>

locations/templates/locations/wall.html
<div id="disqus_thread"></div>
<script type="text/javascript">
    {{ DISQUS_CONFIG }}
    var disqus_shortname = "{{ DISQUS_SHORTNAME }}";
    var disqus_identifier = "location/{{ current_location.id }}";
    var disqus_developer = 0;

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Пожалуйста, активируйте JavaScript, чтобы просматривать <a href="http://disqus.com/?ref_noscript">комментарии</a>.</noscript>

locations/templates/locations/web_observers.html
{% load elements %}
<p>
    <!--Инструкцию о том, как стать веб-наблюдателем можно найти <a href="{% url web_observers_help %}">здесь</a>.
    <br/>
    После выборов мы позволим публиковать ссылки на видео, сделанные пользователями.-->
    Здесь вы можете выложить ссылку на захваченное видео с веб-камер.
</p>

{% button "" "Выложить ссылку на видео" "become_web_observer1" %}

<p>
    <table class="web_observers_table">
        <tr>
            <th style="text-align:left;">Время</th>
            <th>Участник</th>
            <th>Ссылка на видео</th>
        </tr>
        {% for time in times %}
        <tr>
            <td style="text-align:left;" width="30%">{{ time.start_time }}:00 &ndash; {{ time.end_time }}:00</td>
            <td width="35%">
                {% for web_observer in time.web_observers %}
                    {% with participant=web_observer.user %}
                        {% include "elements/participant.html" %}
                    {% endwith %}
                    <br/>
                {% endfor %}
            </td>
            <td>
                {% for web_observer in time.web_observers %}
                    <a href="{{ web_observer.url }}" target="_blank">Видео</a>
                    <br/>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
</p>